### ISSUE TITLE
Optional `Next` adapter for `Iterators`.

### ISSUE THREAD

**Issue by dmfs** [dmfs/optional#5]
For `Iterable` we have the `First` Adapter to represent the optional first element. For an `Iterator` we can't use "First" because we don't know how many elements have been iterated already, but an adequate name would be `Next`.

The big question is: should next be evaluated lazily? Or to put in in code is this the expected behavior?

```java
Iterator<String> i = Arrays.asList("1", "2", "3").iterator();

Optional<String> a = new Next(i);
Optional<String> b = new Next(i);
Optional<String> c = new Next(i);

// which version would you expect
// lazy evaluation? First evaluated gets the `next()` value
assertEquals("1", c.value()); 
assertEquals("2", b.value());
assertEquals("3", a.value());

// or eager evaluation? First created gets the `next()` value
assertEquals("3", c.value()); 
assertEquals("2", b.value());
assertEquals("1", a.value());

// in any case the value should be "stable" and not change after it's been evaluated
assertEquals("1", a.value());
// calling value() again won't change the value
assertEquals("1", a.value());
```

**Comment by lemonboston** [comment]
Good question. I think maybe lazy evaluation. So as I see it the mutability of an `Iterator` is always something we have to keep in mind, so we cannot reuse the original `Iterator`, this is how current `Iterator` decorators work as well as I see. Here it is a bit different because we 'convert' it to an `Optional`, but still when we pass in the `Iterator` we should probably hand over ownership as well.

So we would avoid reusing iterators like this:
```
Optional<String> a = new Next(iterator);
Optional<String> b = new Next(iterator);
Optional<String> c = new Next(iterator);
```
Same as I guess with any other mutable object that would go into a then supposed to be immutable object constructor. Not the best situation in the first place, but if we need to do it, I guess we have to make sure that the mutable object is not used elsewhere, but was created just for that.
I am wondering now whether we should only use `Iterable`s..  would that make sense? All `Iterator` decorators would be internal class to a corresponding `Iterable` decorator. Maybe that way we could keep immutability without loosing anything on lazy evaluation and performance? Just a random thought, I am not sure.

By the way, I can't find the `First` `Iterable` decorator.

**Comment by dmfs** [comment]
The problem is that sometimes it's not possible to provide an `Iterable`. An `Iterable` means you can start over again, but if you operate on a stream that might not be possible. Hence we need these `Iterator` decorators.
In other cases there is really no point in using `Iterable` because you're not going to reiterate.

In general you wouldn't create multiple `Next` from the same `Iterator` that doesn't make sense, you could just iterate it normally instead. This is really just meant as a convenient way of saying "whatever comes next, if anything" when you don't care about whatever comes after that.

So I'm ok with saying that `Next` becomes the owner of the `Iterator`, but there is no way to sanction the continued use of the `Iterator`.

**Comment by lemonboston** [comment]
Ok, I've create the pull request where `Next` takes ownership of the `Iterator`, so it evaluates the value lazily.

**Comment by dmfs** [comment]
Done.
